version: '3'
services:

  ergeon_service:
    build: ./
    image: ergeon_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000